/** Encargos de clientes para la galería de Trabajos realizados. */

export const TRABAJOS_ITEMS = [
  { id: 'cajas-te', titulo: 'Cajas de té', alt: 'Cajas de té personalizadas, grabadas con nombre y fecha' },
  { id: 'caja-truco', titulo: 'Caja de truco', alt: 'Caja de truco de madera grabada con el nombre Omar Odriozola' },
  { id: 'adorno-navidad', titulo: 'Adornos de Navidad', alt: 'Adornos de pesebre para el árbol, empaquetados con moño rojo' },
  { id: 'anotadores', titulo: 'Anotadores', alt: 'Anotadores anillados grabados con nombres y una corona' },
  { id: 'enhebrador-gato', titulo: 'Enhebrador de gato', alt: 'Enhebrador didáctico de madera con forma de gato' },
  { id: 'enhebrador-manzana', titulo: 'Enhebrador de manzana', alt: 'Enhebrador didáctico de madera con forma de manzana' },
  { id: 'centros-mesa', titulo: 'Centros de mesa', alt: 'Centros de mesa con escudo, cortados en serie' },
  { id: 'cuadro-perro', titulo: 'Cuadro personalizado', alt: 'Silueta de perro en la pared, con el nombre Mosqueton' },
  { id: 'exhibidor', titulo: 'Exhibidor', alt: 'Exhibidor de mostrador para Carey Hojillas y Accesorios' },
  { id: 'fichero', titulo: 'Fichero', alt: 'Fichero de madera grabado con el logo de Volka Fit' },
  { id: 'figuras-pintar-1', titulo: 'Figuras para pintar', alt: 'Figuras de madera para pintar: unicornio, Sonic y camiseta de Messi' },
  { id: 'figuras-pintar-2', titulo: 'Figuras para pintar', alt: 'Figuras de helados de madera para pintar' },
  { id: 'medallas', titulo: 'Medallas', alt: 'Medallas de MDF con cinta celeste y blanca para un torneo de box' },
  { id: 'organizador-escritorio', titulo: 'Organizador de escritorio', alt: 'Organizador de escritorio blanco, con cajón y divisores' },
  { id: 'memotest', titulo: 'Memotest', alt: 'Fichas de memotest de madera, grabadas con personajes' },
  { id: 'llaveros-moto', titulo: 'Llaveros', alt: 'Llaveros de moto personalizados para un cumpleaños' },
  { id: 'portacelulares', titulo: 'Portacelulares', alt: 'Tres soportes para celular, de madera pintada de negro' },
  { id: 'portallaves-familia', titulo: 'Portallaves', alt: 'Portallaves de casita con una frase de familia y cinco ganchos' },
  { id: 'portacinturones', titulo: 'Portacinturones de karate', alt: 'Porta cinturones de karate, negro, con siluetas de luchadores' },
  { id: 'porta-sahumerio', titulo: 'Porta sahumerio', alt: 'Porta sahumerio para Triple F, con figuras de nenas y nene' },
  { id: 'portamedallas', titulo: 'Portamedallas', alt: 'Portamedallas personalizado con el nombre Alexis' },
  { id: 'portallaves-boca', titulo: 'Portallaves', alt: 'Portallaves de Boca Juniors, con el escudo y la bombonera' },
  { id: 'portaretratos', titulo: 'Portaretratos', alt: 'Portaretratos de madera grabados con un arbolito de Navidad' },
  { id: 'reglas', titulo: 'Reglas personalizadas', alt: 'Reglas de madera grabadas con el nombre EMA y un corazón' },
  { id: 'portasahumerios', titulo: 'Portasahumerios', alt: 'Lote de portasahumerios blancos y de madera, apilados' },
  { id: 'tablero-pendulo', titulo: 'Tablero para péndulo', alt: 'Tablero circular para péndulo, con un sol grabado' },
  { id: 'tapas-velas', titulo: 'Tapas para velas', alt: 'Tapas circulares de madera para velas, con el logo de Hijas' },
  { id: 'trofeo-bailarina', titulo: 'Trofeo de bailarina', alt: 'Trofeo de madera con forma de bailarina y el nombre Mora' },
  { id: 'trabado', titulo: 'Trabado', alt: 'Juego trabado de madera para Colonia Judiciales' },
  { id: 'rompecabezas', titulo: 'Rompecabezas', alt: 'Rompecabezas de madera con animales, para Colonia Judiciales' },
  { id: 'tateti', titulo: 'Tatetí', alt: 'Tatetí de madera para Colonia Judiciales' },
] as const;
